### ISSUE TITLE
child processes continue after timeout

### ISSUE THREAD

**Issue by pbnjay** [joiningdata/qcd#2]
Steven noticed high CPU usage even when python testing code had finished running, 
@zvandehy it looks like when the timeout expires the process continues in the background but results are discarded.

https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate

> The child process is not killed if the timeout expires, so in order to cleanup properly a well-behaved application should kill the child process and finish communication

**Comment by zvandehy** [comment]
added kill statement
